add review
Maksym-Ocheretniuk/team-minicoder pull request #7
Opened 2022-12-24 17:25 UTC by lonaver

мають бути підключені таки скрипти
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>

    <script src="./js/slick.min.js"></script>
    <script src="./js/script.js"></script>
 два файла знаходяться в папці ікс, без підключення скриптов буде видно всі відгуки

2022-12-25 15:51 UTC, lonaver commented
я по інакшому зробила ) попереднє відміняється, треба зробити так:
в файл index.js
тільки оце
import './js/script';
2)в index.html додати в header над запуском <!-- JS -->
    <!-- swiper -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"
    />
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
//////////////////////////
    <!-- JS -->
    <script type="module" src="./index.js"></script>

2022-12-25 23:17 UTC, DiBaranovska requested changes

2022-12-25 23:17 UTC, DiBaranovska commented on src/partials/reviews.html
> +            class="reviews__img img"
не знайшла у коді клас img, у базових стилях, стилі для картинок додаються до атрибута тега, тож Вам не потрібно його вставляти у класс

2022-12-25 23:17 UTC, DiBaranovska commented on src/sass/_reviews.scss
> +  @media screen and (min-width: 768px) {
тут Ви двічі задали медіаправило для екрана від 768, має бути від 1200, також додайте верхні паддінги. Я знаю що коли збирались то говорили що це я маю зробити, але Максим сказав мені видалити, і що домовились коли секції збігаються той хто робить нижню задає верхні падінги, ось мій кусочок коду що я видалила, Вам тільки на top переробити
    padding-bottom: 80px;
  @media screen and (min-width: 768px) {
    padding-bottom: 100px;
  }

  @media screen and (min-width: 1200px) {
    padding-bottom: 140px;
  }

2022-12-25 23:17 UTC, DiBaranovska commented on src/sass/_reviews.scss
> +  font-weight: 500;
font-weight для мобільних тел 400

2022-12-25 23:48 UTC, DiBaranovska requested changes

2022-12-25 23:48 UTC, DiBaranovska commented on src/partials/reviews.html
> +            "
на цій картинці Ви видалили атрибут src картинки, валідатор це не пропускає

2022-12-25 23:48 UTC, DiBaranovska commented on src/partials/reviews.html
> +            data-lazy="./images/reviews/pexels-nappy-936000@1x.jpg"
тут також немає атрибуту src

2022-12-26 07:42 UTC, lonaver commented
Дякую за перевірку ) зміни зробила, 
на рахунок атрибуту src, це була заміна для запуску js,
тому треба було щоб стояло саме data-lazy,
але я замінила js, тому це вже не актуально )
поставила знову src

2022-12-26 07:48 UTC, lonaver commented
щодо приписаного  базового стилю img {
  display: block;
  max-width: 100%;
  height: auto;
}
мені здається мало би бути  img {
  display: block;
  margin: 0px;
  width: 100%;
  height: auto;
}

2022-12-26 11:32 UTC, lonaver commented
додала нижні падінги на секцію

2022-12-26 20:43 UTC, Maksym-Ocheretniuk approved these changes

2022-12-26 20:47 UTC, Maksym-Ocheretniuk approved these changes

2022-12-26 20:47 UTC, merged